/**
 * Every external dependency sits behind one of these interfaces, and every one
 * of them declares whether it can bill me. See `guard.ts`.
 */
export interface ProviderDescriptor {
  /** Stable id used in `runs.provider` and in the UI's "generated by" badge. */
  readonly id: string;
  readonly kind: 'llm' | 'scraper' | 'image' | 'publishing';
  /**
   * True if this provider can produce a bill under any configuration — not
   * "will it bill me today". A free tier on a billable account is still true
   * unless the account cannot be charged at all.
   */
  readonly costsMoney: boolean;
  /** Human-readable note shown in Settings next to the monthly total. */
  readonly costNote: string;
}

export interface ProviderHealth {
  ok: boolean;
  detail: string;
}

export interface Provider extends ProviderDescriptor {
  health(): Promise<ProviderHealth>;
}
